import { Container, SimpleGrid } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { InspTripListItem } from "../components/trips/trip-list-item";
import { getTrips } from "../data/trips/trips.client";
import { TripListItem, TripListResponse } from "../data/trips/trips.model";
import styles from "../styles/Home.module.css";

const Trips: NextPage = () => {
  const [trips, setTrips] = useState([] as TripListItem[]);
  useEffect(() => {
    getTrips().then((tripsResponse) => {
      setTrips(tripsResponse.tripSet);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Yeehaw Trips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="1200px">
          <h1 className={styles.title}>Trips</h1>
          <SimpleGrid minChildWidth="350px" spacing="40px">
            {trips.map((trip, index) => (
              <InspTripListItem trip={trip} key={index} />
            ))}
          </SimpleGrid>
        </Container>
      </main>
    </div>
  );
};

export default Trips;
